### ISSUE TITLE
出库管理-出库单查询：检索条件中的【物流单号】输入信息查询无效

### ISSUE THREAD

**Issue by shupingxiang** [CFA-WMS/WMS-BugResposity#108]
在【物流单号】的输入框中输入一个单号，点击查询，查询无效，结果页面显示的是所有的数据。且在出库单查询的页面，不管是查询结果列表页面还是某个单的详细页面，都没有“物流单号”的栏位，这个栏位是否还有必要存在？

**Comment by shupingxiang** [comment]
仍有问题

**Comment by wanderhe** [comment]
新導入單據正常，歷史單據無需理會
