### ISSUE TITLE
入庫管理-到貨通知單-Excel导入失败

### ISSUE THREAD

**Issue by jedichou** [CFA-WMS/WMS-BugResposity#118]
* 點擊【excel導入】，在彈出框中點擊下載魔板，打開魔板更新一條數據保存后，點擊上傳確認后，在查詢結果列表中看不到導入的數據，數據總量沒有增加，數據庫中也沒有
*  ShuPing-2016.5.4

**Comment by wanderhe** [comment]
請重新下載模板

**Comment by shupingxiang** [comment]
目前导入仍有问题，导入不成功
