### ISSUE TITLE
出库管理-出库单查询-Excel导入及相关提示问题

### ISSUE THREAD

**Issue by jedichou** [CFA-WMS/WMS-BugResposity#140]
* excel导入功能，下载的模板没有示例，填写不方便。在每个字段随便输入信息都能导入成功。点击“出库单导入”页面的  excel导入  按钮弹出的提示框为英文。点击“确认”按钮没反应。
* ShuPing-2016.5.5

**Comment by wanderhe** [comment]
請重新下載模板

**Comment by shupingxiang** [comment]
重新下载模板导入仍有问题，必填项都有按照要求填写，但导入时系统识别成“为空”。如需相应导入的数据请告知
